#nullable enable

using HaruChat.Runtime.LocalModels;
using System;
using System.Collections.Generic;
using System.Runtime.InteropServices;
using Microsoft.Win32.SafeHandles;
using System.Text;
using System.Threading;
using System.Threading.Tasks;

namespace HaruChat.LlamaCpp
{
    /// <summary>P/Invoke-only implementation. No model-family or prompt policy belongs here.</summary>
    public sealed class LlamaCppBackend : ILocalModelBackend
    {
        private readonly object _gate = new object(); private ulong _next = 1;
        // The public port intentionally exposes opaque value IDs. Native pointers stay in SafeHandle ownership wrappers.
        private readonly Dictionary<ulong, NativeSafeHandle> _runtimes = new Dictionary<ulong, NativeSafeHandle>(); private readonly Dictionary<ulong, NativeSafeHandle> _models = new Dictionary<ulong, NativeSafeHandle>(); private readonly Dictionary<ulong, NativeSafeHandle> _contexts = new Dictionary<ulong, NativeSafeHandle>(); private readonly Dictionary<ulong, NativeSafeHandle> _jobs = new Dictionary<ulong, NativeSafeHandle>(); private bool _disposed;
        public Task<LocalBackendResult<LocalRuntimeHandle>> CreateRuntimeAsync(LocalRuntimeOptions options, CancellationToken ct) { return Task.Run(() => { ct.ThrowIfCancellationRequested(); var o = new RuntimeOptions { struct_size = (uint)Marshal.SizeOf<RuntimeOptions>(), abi_version = Abi, event_queue_capacity = (uint)options.MaximumQueuedEventCount }; var status = Native.runtime_create(ref o, out var ptr); if (status != 0) return Fail<LocalRuntimeHandle>(status); lock (_gate) { var id = _next++; _runtimes[id] = new NativeSafeHandle(ptr, Native.runtime_destroy); return LocalBackendResult<LocalRuntimeHandle>.Success(new LocalRuntimeHandle(id)); } }, ct); }
        public Task<LocalBackendResult> DestroyRuntimeAsync(LocalRuntimeHandle runtime, CancellationToken ct) { return Task.Run(() => Destroy(_runtimes, runtime.Value, Native.runtime_destroy), ct); }
        public Task<LocalBackendResult<LocalRuntimeMetadata>> GetRuntimeMetadataAsync(LocalRuntimeHandle runtime, CancellationToken ct) { lock (_gate) { if (!_runtimes.TryGetValue(runtime.Value, out var ptr)) return Task.FromResult(LocalBackendResult<LocalRuntimeMetadata>.Failure(LocalBackendErrorCode.InvalidHandle, "Invalid runtime.")); var m = new RuntimeMetadata { struct_size = (uint)Marshal.SizeOf<RuntimeMetadata>(), abi_version = Abi }; var status = Native.runtime_metadata(ptr.Pointer, ref m); var flags = m.capability_flags; return Task.FromResult(status == 0 ? LocalBackendResult<LocalRuntimeMetadata>.Success(new LocalRuntimeMetadata(m.backend_name ?? string.Empty, m.target_triple ?? string.Empty, (flags & 1) != 0, (flags & 2) != 0, (flags & 4) != 0)) : Fail<LocalRuntimeMetadata>(status)); } }
        public Task<LocalBackendResult<LocalModelHandle>> LoadModelAsync(LocalRuntimeHandle runtime, LocalModelLoadOptions options, CancellationToken ct) { return Task.Run(() => { ct.ThrowIfCancellationRequested(); lock (_gate) { if (!_runtimes.TryGetValue(runtime.Value, out var parent)) return LocalBackendResult<LocalModelHandle>.Failure(LocalBackendErrorCode.InvalidHandle, "Invalid runtime."); var o = new ModelLoadOptions { struct_size = (uint)Marshal.SizeOf<ModelLoadOptions>(), abi_version = Abi }; var status = Native.model_load(parent.Pointer, options.ModelPath, ref o, out var ptr); if (status != 0) return Fail<LocalModelHandle>(status); var id = _next++; _models[id] = new NativeSafeHandle(ptr, Native.model_unload); return LocalBackendResult<LocalModelHandle>.Success(new LocalModelHandle(id)); } }, ct); }
        public Task<LocalBackendResult> UnloadModelAsync(LocalModelHandle model, CancellationToken ct) { return Task.Run(() => Destroy(_models, model.Value, Native.model_unload), ct); }
        public Task<LocalBackendResult<LocalContextHandle>> CreateContextAsync(LocalModelHandle model, LocalContextOptions options, CancellationToken ct) { return Task.Run(() => { ct.ThrowIfCancellationRequested(); lock (_gate) { if (!_models.TryGetValue(model.Value, out var parent)) return LocalBackendResult<LocalContextHandle>.Failure(LocalBackendErrorCode.InvalidHandle, "Invalid model."); var o = new ContextOptions { struct_size = (uint)Marshal.SizeOf<ContextOptions>(), abi_version = Abi, context_size = (uint)options.ContextWindowTokens, batch_size = (uint)options.BatchSize }; var status = Native.context_create(parent.Pointer, ref o, out var ptr); if (status != 0) return Fail<LocalContextHandle>(status); var id = _next++; _contexts[id] = new NativeSafeHandle(ptr, Native.context_destroy); return LocalBackendResult<LocalContextHandle>.Success(new LocalContextHandle(id)); } }, ct); }
        public Task<LocalBackendResult> ResetContextAsync(LocalContextHandle context, CancellationToken ct) { return Task.Run(() => Call(_contexts, context.Value, Native.context_reset), ct); }
        public Task<LocalBackendResult> DestroyContextAsync(LocalContextHandle context, CancellationToken ct) { return Task.Run(() => Destroy(_contexts, context.Value, Native.context_destroy), ct); }
        public Task<LocalBackendResult<LocalGenerationHandle>> StartGenerationAsync(LocalContextHandle context, LocalGenerationOptions options, CancellationToken ct) { return Task.Run(() => { ct.ThrowIfCancellationRequested(); lock (_gate) { if (!_contexts.TryGetValue(context.Value, out var parent)) return LocalBackendResult<LocalGenerationHandle>.Failure(LocalBackendErrorCode.InvalidHandle, "Invalid context."); var utf8 = Encoding.UTF8.GetBytes(options.Prompt); var handle = GCHandle.Alloc(utf8, GCHandleType.Pinned); try { var o = new GenerationOptions { struct_size = (uint)Marshal.SizeOf<GenerationOptions>(), abi_version = Abi, prompt_utf8 = handle.AddrOfPinnedObject(), prompt_bytes = (uint)utf8.Length, max_tokens = (uint)options.MaximumOutputTokens, temperature = options.Temperature, top_k = (uint)options.TopK, top_p = options.TopP, seed = options.Seed }; var status = Native.job_start(parent.Pointer, ref o, out var ptr); if (status != 0) return Fail<LocalGenerationHandle>(status); var id = _next++; _jobs[id] = new NativeSafeHandle(ptr, Native.job_destroy); return LocalBackendResult<LocalGenerationHandle>.Success(new LocalGenerationHandle(id)); } finally { handle.Free(); } } }, ct); }
        public Task<LocalBackendResult<LocalEventBatch>> PollEventsAsync(LocalGenerationHandle generation, int maximumEventCount, CancellationToken ct) { return Task.Run(() => PollEvents(generation, maximumEventCount, ct), ct); }
        private LocalBackendResult<LocalEventBatch> PollEvents(LocalGenerationHandle generation, int maximumEventCount, CancellationToken ct) { if (maximumEventCount <= 0) return LocalBackendResult<LocalEventBatch>.Failure(LocalBackendErrorCode.InvalidArgument, "Maximum event count must be positive."); lock (_gate) { if (!_jobs.TryGetValue(generation.Value, out var job)) return LocalBackendResult<LocalEventBatch>.Failure(LocalBackendErrorCode.InvalidHandle, "Invalid generation."); var events = new List<LocalBackendEvent>(); for (var i = 0; i < maximumEventCount; i++) { ct.ThrowIfCancellationRequested(); var e = new Event { struct_size = (uint)Marshal.SizeOf<Event>(), abi_version = Abi }; var status = Native.job_poll(job.Pointer, ref e); if (status == 6) break; if (status != 0) return Fail<LocalEventBatch>(status); var payload = new byte[e.payload_bytes]; if (e.payload_utf8 != IntPtr.Zero && e.payload_bytes > 0) Marshal.Copy(e.payload_utf8, payload, 0, payload.Length); var error = e.type == 5 ? new LocalBackendError(LocalBackendErrorCode.BackendFailure, Encoding.UTF8.GetString(payload)) : default; events.Add(new LocalBackendEvent((LocalBackendEventKind)(e.type - 1), (long)e.sequence, payload, error, new LocalGenerationMetrics(0, (long)e.metrics.emitted_token_count, TimeSpan.FromMilliseconds(e.metrics.elapsed_milliseconds)))); } return LocalBackendResult<LocalEventBatch>.Success(new LocalEventBatch(events)); } }
        public Task<LocalBackendResult> CancelGenerationAsync(LocalGenerationHandle generation, CancellationToken ct) { return Task.Run(() => Call(_jobs, generation.Value, Native.job_cancel), ct); }
        public Task<LocalBackendResult> DestroyGenerationAsync(LocalGenerationHandle generation, CancellationToken ct) { return Task.Run(() => Destroy(_jobs, generation.Value, Native.job_destroy), ct); }
        public Task<LocalBackendResult<LocalModelMetadata>> GetModelMetadataAsync(LocalModelHandle model, CancellationToken ct) { lock (_gate) { if (!_models.TryGetValue(model.Value, out var ptr)) return Task.FromResult(LocalBackendResult<LocalModelMetadata>.Failure(LocalBackendErrorCode.InvalidHandle, "Invalid model.")); var m = new ModelMetadata { struct_size = (uint)Marshal.SizeOf<ModelMetadata>(), abi_version = Abi }; var status = Native.model_metadata(ptr.Pointer, ref m); return Task.FromResult(status == 0 ? LocalBackendResult<LocalModelMetadata>.Success(new LocalModelMetadata(m.description ?? string.Empty, (int)m.training_context_tokens)) : Fail<LocalModelMetadata>(status)); } }
        public Task<LocalBackendResult<LocalGenerationMetrics>> GetGenerationMetricsAsync(LocalGenerationHandle generation, CancellationToken ct) { return Task.FromResult(LocalBackendResult<LocalGenerationMetrics>.Failure(LocalBackendErrorCode.Unsupported, "Metrics are emitted with events.")); }
        public ValueTask DisposeAsync()
        {
            lock (_gate)
            {
                if (_disposed) return default;
                _disposed = true;
                DisposeAll(_jobs); DisposeAll(_contexts); DisposeAll(_models); DisposeAll(_runtimes);
                return default;
            }
        }
        private bool Try(Dictionary<ulong, NativeSafeHandle> map, ulong id, out IntPtr value) { lock (_gate) { if (map.TryGetValue(id, out var handle) && !handle.IsInvalid && !handle.IsClosed) { value = handle.Pointer; return true; } value = IntPtr.Zero; return false; } }
        private LocalBackendResult Call(Dictionary<ulong, NativeSafeHandle> map, ulong id, Func<IntPtr, int> call) { lock (_gate) { if (!map.TryGetValue(id, out var handle) || handle.IsClosed) return LocalBackendResult.Failure(LocalBackendErrorCode.InvalidHandle, "Invalid handle."); var s = call(handle.Pointer); return s == 0 ? LocalBackendResult.Success() : Fail(s); } }
        private LocalBackendResult Destroy(Dictionary<ulong, NativeSafeHandle> map, ulong id, Func<IntPtr, int> call) { lock (_gate) { if (!map.TryGetValue(id, out var handle)) return LocalBackendResult.Failure(LocalBackendErrorCode.InvalidHandle, "Invalid handle."); handle.Dispose(); map.Remove(id); return LocalBackendResult.Success(); } }
        private static void DisposeAll(Dictionary<ulong, NativeSafeHandle> map) { foreach (var handle in map.Values) handle.Dispose(); map.Clear(); }
        private sealed class NativeSafeHandle : SafeHandleZeroOrMinusOneIsInvalid
        {
            private readonly Func<IntPtr, int> _release;
            public NativeSafeHandle(IntPtr pointer, Func<IntPtr, int> release) : base(true) { _release = release; SetHandle(pointer); }
            public IntPtr Pointer { get { return DangerousGetHandle(); } }
            protected override bool ReleaseHandle() { return _release(handle) == 0; }
        }
        private static LocalBackendResult Fail(int status) { return LocalBackendResult.Failure(Map(status), "Native error " + status + "."); }
        private static LocalBackendResult<T> Fail<T>(int status) { return LocalBackendResult<T>.Failure(Map(status), "Native error " + status + "."); }
        private static LocalBackendErrorCode Map(int status) { switch (status) { case 1: return LocalBackendErrorCode.InvalidArgument; case 2: return LocalBackendErrorCode.InvalidHandle; case 4: return LocalBackendErrorCode.NotFound; case 5: return LocalBackendErrorCode.Busy; case 7: return LocalBackendErrorCode.Cancelled; case 8: return LocalBackendErrorCode.Unsupported; default: return LocalBackendErrorCode.BackendFailure; } }
        private const uint Abi = 0x00010000;
        [StructLayout(LayoutKind.Sequential)] private struct RuntimeOptions { public uint struct_size, abi_version, event_queue_capacity, reserved; }
        [StructLayout(LayoutKind.Sequential)] private struct ModelLoadOptions { public uint struct_size, abi_version, reserved0, reserved1; }
        [StructLayout(LayoutKind.Sequential)] private struct ContextOptions { public uint struct_size, abi_version, context_size, reserved, batch_size, reserved1; }
        [StructLayout(LayoutKind.Sequential)] private struct GenerationOptions { public uint struct_size, abi_version; public IntPtr prompt_utf8; public uint prompt_bytes; public IntPtr mock_response_utf8; public uint mock_response_bytes, max_tokens, token_delay_ms; public float temperature, top_p; public uint top_k, seed; }
        [StructLayout(LayoutKind.Sequential, CharSet = CharSet.Ansi)] private struct RuntimeMetadata { public uint struct_size, abi_version, capability_flags, reserved; [MarshalAs(UnmanagedType.ByValTStr, SizeConst = 32)] public string? backend_name; [MarshalAs(UnmanagedType.ByValTStr, SizeConst = 64)] public string? target_triple; }
        [StructLayout(LayoutKind.Sequential, CharSet = CharSet.Ansi)] private struct ModelMetadata { public uint struct_size, abi_version, training_context_tokens, reserved; [MarshalAs(UnmanagedType.ByValTStr, SizeConst = 128)] public string? description; }
        [StructLayout(LayoutKind.Sequential)] private struct Metrics { public uint struct_size, abi_version; public ulong emitted_token_count, queue_depth, elapsed_milliseconds; }
        [StructLayout(LayoutKind.Sequential)] private struct Event { public uint struct_size, abi_version, type, is_terminal; public ulong sequence; public IntPtr payload_utf8; public uint payload_bytes, reserved; public Metrics metrics; }
        private static class Native { private const string Lib = "llmcore"; [DllImport(Lib, EntryPoint = "hc_llm_runtime_create")] internal static extern int runtime_create(ref RuntimeOptions o, out IntPtr h); [DllImport(Lib, EntryPoint = "hc_llm_runtime_get_metadata")] internal static extern int runtime_metadata(IntPtr h, ref RuntimeMetadata m); [DllImport(Lib, EntryPoint = "hc_llm_runtime_destroy")] internal static extern int runtime_destroy(IntPtr h); [DllImport(Lib, EntryPoint = "hc_llm_model_load", CharSet = CharSet.Ansi)] internal static extern int model_load(IntPtr r, string p, ref ModelLoadOptions o, out IntPtr h); [DllImport(Lib, EntryPoint = "hc_llm_model_unload")] internal static extern int model_unload(IntPtr h); [DllImport(Lib, EntryPoint = "hc_llm_model_get_metadata")] internal static extern int model_metadata(IntPtr h, ref ModelMetadata m); [DllImport(Lib, EntryPoint = "hc_llm_context_create")] internal static extern int context_create(IntPtr m, ref ContextOptions o, out IntPtr h); [DllImport(Lib, EntryPoint = "hc_llm_context_reset")] internal static extern int context_reset(IntPtr h); [DllImport(Lib, EntryPoint = "hc_llm_context_destroy")] internal static extern int context_destroy(IntPtr h); [DllImport(Lib, EntryPoint = "hc_llm_job_start")] internal static extern int job_start(IntPtr c, ref GenerationOptions o, out IntPtr h); [DllImport(Lib, EntryPoint = "hc_llm_job_cancel")] internal static extern int job_cancel(IntPtr h); [DllImport(Lib, EntryPoint = "hc_llm_job_poll")] internal static extern int job_poll(IntPtr h, ref Event e); [DllImport(Lib, EntryPoint = "hc_llm_job_destroy")] internal static extern int job_destroy(IntPtr h); }
    }
}
