#nullable enable

using HaruChat.Runtime.LocalModels;
using System;
using System.Collections.Generic;
using System.Runtime.InteropServices;
using System.Text;
using System.Threading;
using System.Threading.Tasks;

namespace HaruChat.LlamaCpp
{
    /// <summary>P/Invoke-only implementation. No model-family or prompt policy belongs here.</summary>
    public sealed class LlamaCppBackend : ILocalModelBackend
    {
        private readonly object _gate = new object(); private ulong _next = 1;
        private readonly Dictionary<ulong, IntPtr> _runtimes = new Dictionary<ulong, IntPtr>(); private readonly Dictionary<ulong, IntPtr> _models = new Dictionary<ulong, IntPtr>(); private readonly Dictionary<ulong, IntPtr> _contexts = new Dictionary<ulong, IntPtr>(); private readonly Dictionary<ulong, IntPtr> _jobs = new Dictionary<ulong, IntPtr>();
        public Task<LocalBackendResult<LocalRuntimeHandle>> CreateRuntimeAsync(LocalRuntimeOptions options, CancellationToken ct) { ct.ThrowIfCancellationRequested(); var o = new RuntimeOptions { struct_size = (uint)Marshal.SizeOf<RuntimeOptions>(), abi_version = Abi, event_queue_capacity = (uint)options.MaximumQueuedEventCount }; var status = Native.runtime_create(ref o, out var ptr); if (status != 0) return Task.FromResult(Fail<LocalRuntimeHandle>(status)); lock (_gate) { var id = _next++; _runtimes[id] = ptr; return Task.FromResult(LocalBackendResult<LocalRuntimeHandle>.Success(new LocalRuntimeHandle(id))); } }
        public Task<LocalBackendResult> DestroyRuntimeAsync(LocalRuntimeHandle runtime, CancellationToken ct) { return Task.FromResult(Destroy(_runtimes, runtime.Value, Native.runtime_destroy)); }
        public Task<LocalBackendResult<LocalModelHandle>> LoadModelAsync(LocalRuntimeHandle runtime, LocalModelLoadOptions options, CancellationToken ct) { ct.ThrowIfCancellationRequested(); if (!Try(_runtimes, runtime.Value, out var parent)) return Task.FromResult(LocalBackendResult<LocalModelHandle>.Failure(LocalBackendErrorCode.InvalidHandle, "Invalid runtime.")); var o = new ModelLoadOptions { struct_size = (uint)Marshal.SizeOf<ModelLoadOptions>(), abi_version = Abi }; var status = Native.model_load(parent, options.ModelPath, ref o, out var ptr); if (status != 0) return Task.FromResult(Fail<LocalModelHandle>(status)); lock (_gate) { var id = _next++; _models[id] = ptr; return Task.FromResult(LocalBackendResult<LocalModelHandle>.Success(new LocalModelHandle(id))); } }
        public Task<LocalBackendResult> UnloadModelAsync(LocalModelHandle model, CancellationToken ct) { return Task.FromResult(Destroy(_models, model.Value, Native.model_unload)); }
        public Task<LocalBackendResult<LocalContextHandle>> CreateContextAsync(LocalModelHandle model, LocalContextOptions options, CancellationToken ct) { ct.ThrowIfCancellationRequested(); if (!Try(_models, model.Value, out var parent)) return Task.FromResult(LocalBackendResult<LocalContextHandle>.Failure(LocalBackendErrorCode.InvalidHandle, "Invalid model.")); var o = new ContextOptions { struct_size = (uint)Marshal.SizeOf<ContextOptions>(), abi_version = Abi, context_size = (uint)options.ContextWindowTokens, batch_size = (uint)options.BatchSize }; var status = Native.context_create(parent, ref o, out var ptr); if (status != 0) return Task.FromResult(Fail<LocalContextHandle>(status)); lock (_gate) { var id = _next++; _contexts[id] = ptr; return Task.FromResult(LocalBackendResult<LocalContextHandle>.Success(new LocalContextHandle(id))); } }
        public Task<LocalBackendResult> ResetContextAsync(LocalContextHandle context, CancellationToken ct) { return Task.FromResult(Call(_contexts, context.Value, Native.context_reset)); }
        public Task<LocalBackendResult> DestroyContextAsync(LocalContextHandle context, CancellationToken ct) { return Task.FromResult(Destroy(_contexts, context.Value, Native.context_destroy)); }
        public Task<LocalBackendResult<LocalGenerationHandle>> StartGenerationAsync(LocalContextHandle context, LocalGenerationOptions options, CancellationToken ct) { ct.ThrowIfCancellationRequested(); if (!Try(_contexts, context.Value, out var parent)) return Task.FromResult(LocalBackendResult<LocalGenerationHandle>.Failure(LocalBackendErrorCode.InvalidHandle, "Invalid context.")); var utf8 = Encoding.UTF8.GetBytes(options.Prompt); var handle = GCHandle.Alloc(utf8, GCHandleType.Pinned); try { var o = new GenerationOptions { struct_size = (uint)Marshal.SizeOf<GenerationOptions>(), abi_version = Abi, prompt_utf8 = handle.AddrOfPinnedObject(), prompt_bytes = (uint)utf8.Length, max_tokens = (uint)options.MaximumOutputTokens, temperature = options.Temperature, top_k = (uint)options.TopK, top_p = options.TopP, seed = options.Seed }; var status = Native.job_start(parent, ref o, out var ptr); if (status != 0) return Task.FromResult(Fail<LocalGenerationHandle>(status)); lock (_gate) { var id = _next++; _jobs[id] = ptr; return Task.FromResult(LocalBackendResult<LocalGenerationHandle>.Success(new LocalGenerationHandle(id))); } } finally { handle.Free(); } }
        public async Task<LocalBackendResult<LocalEventBatch>> PollEventsAsync(LocalGenerationHandle generation, int maximumEventCount, CancellationToken ct) { if (!Try(_jobs, generation.Value, out var job)) return LocalBackendResult<LocalEventBatch>.Failure(LocalBackendErrorCode.InvalidHandle, "Invalid generation."); var events = new List<LocalBackendEvent>(); for (var i = 0; i < maximumEventCount; i++) { ct.ThrowIfCancellationRequested(); var e = new Event { struct_size = (uint)Marshal.SizeOf<Event>(), abi_version = Abi }; var status = Native.job_poll(job, ref e); if (status == 6) break; if (status != 0) return Fail<LocalEventBatch>(status); var payload = new byte[e.payload_bytes]; if (e.payload_utf8 != IntPtr.Zero && e.payload_bytes > 0) Marshal.Copy(e.payload_utf8, payload, 0, payload.Length); events.Add(new LocalBackendEvent((LocalBackendEventKind)(e.type - 1), (long)e.sequence, payload, default, new LocalGenerationMetrics(0, (long)e.metrics.emitted_token_count, TimeSpan.FromMilliseconds(e.metrics.elapsed_milliseconds)))); } await Task.Yield(); return LocalBackendResult<LocalEventBatch>.Success(new LocalEventBatch(events)); }
        public Task<LocalBackendResult> CancelGenerationAsync(LocalGenerationHandle generation, CancellationToken ct) { return Task.FromResult(Call(_jobs, generation.Value, Native.job_cancel)); }
        public Task<LocalBackendResult> DestroyGenerationAsync(LocalGenerationHandle generation, CancellationToken ct) { return Task.FromResult(Destroy(_jobs, generation.Value, Native.job_destroy)); }
        public Task<LocalBackendResult<LocalModelMetadata>> GetModelMetadataAsync(LocalModelHandle model, CancellationToken ct) { if (!Try(_models, model.Value, out var ptr)) return Task.FromResult(LocalBackendResult<LocalModelMetadata>.Failure(LocalBackendErrorCode.InvalidHandle, "Invalid model.")); var m = new ModelMetadata { struct_size = (uint)Marshal.SizeOf<ModelMetadata>(), abi_version = Abi }; var status = Native.model_metadata(ptr, ref m); return Task.FromResult(status == 0 ? LocalBackendResult<LocalModelMetadata>.Success(new LocalModelMetadata(m.description ?? string.Empty, (int)m.training_context_tokens)) : Fail<LocalModelMetadata>(status)); }
        public Task<LocalBackendResult<LocalGenerationMetrics>> GetGenerationMetricsAsync(LocalGenerationHandle generation, CancellationToken ct) { return Task.FromResult(LocalBackendResult<LocalGenerationMetrics>.Failure(LocalBackendErrorCode.Unsupported, "Metrics are emitted with events.")); }
        public ValueTask DisposeAsync() { foreach (var j in new List<ulong>(_jobs.Keys)) Destroy(_jobs, j, Native.job_destroy); foreach (var c in new List<ulong>(_contexts.Keys)) Destroy(_contexts, c, Native.context_destroy); foreach (var m in new List<ulong>(_models.Keys)) Destroy(_models, m, Native.model_unload); foreach (var r in new List<ulong>(_runtimes.Keys)) Destroy(_runtimes, r, Native.runtime_destroy); return default; }
        private bool Try(Dictionary<ulong, IntPtr> map, ulong id, out IntPtr value) { lock (_gate) return map.TryGetValue(id, out value); }
        private LocalBackendResult Call(Dictionary<ulong, IntPtr> map, ulong id, Func<IntPtr, int> call) { if (!Try(map, id, out var ptr)) return LocalBackendResult.Failure(LocalBackendErrorCode.InvalidHandle, "Invalid handle."); var s = call(ptr); return s == 0 ? LocalBackendResult.Success() : Fail(s); }
        private LocalBackendResult Destroy(Dictionary<ulong, IntPtr> map, ulong id, Func<IntPtr, int> call) { lock (_gate) { if (!map.TryGetValue(id, out var ptr)) return LocalBackendResult.Failure(LocalBackendErrorCode.InvalidHandle, "Invalid handle."); var s = call(ptr); if (s == 0) map.Remove(id); return s == 0 ? LocalBackendResult.Success() : Fail(s); } }
        private static LocalBackendResult Fail(int status) { return LocalBackendResult.Failure(Map(status), "Native error " + status + "."); }
        private static LocalBackendResult<T> Fail<T>(int status) { return LocalBackendResult<T>.Failure(Map(status), "Native error " + status + "."); }
        private static LocalBackendErrorCode Map(int status) { switch (status) { case 1: return LocalBackendErrorCode.InvalidArgument; case 2: return LocalBackendErrorCode.InvalidHandle; case 4: return LocalBackendErrorCode.NotFound; case 5: return LocalBackendErrorCode.Busy; case 7: return LocalBackendErrorCode.Cancelled; case 8: return LocalBackendErrorCode.Unsupported; default: return LocalBackendErrorCode.BackendFailure; } }
        private const uint Abi = 0x00010000;
        [StructLayout(LayoutKind.Sequential)] private struct RuntimeOptions { public uint struct_size, abi_version, event_queue_capacity, reserved; }
        [StructLayout(LayoutKind.Sequential)] private struct ModelLoadOptions { public uint struct_size, abi_version, reserved0, reserved1; }
        [StructLayout(LayoutKind.Sequential)] private struct ContextOptions { public uint struct_size, abi_version, context_size, reserved, batch_size, reserved1; }
        [StructLayout(LayoutKind.Sequential)] private struct GenerationOptions { public uint struct_size, abi_version; public IntPtr prompt_utf8; public uint prompt_bytes; public IntPtr mock_response_utf8; public uint mock_response_bytes, max_tokens, token_delay_ms; public float temperature, top_p; public uint top_k, seed; }
        [StructLayout(LayoutKind.Sequential, CharSet = CharSet.Ansi)] private struct ModelMetadata { public uint struct_size, abi_version, training_context_tokens, reserved; [MarshalAs(UnmanagedType.ByValTStr, SizeConst = 128)] public string? description; }
        [StructLayout(LayoutKind.Sequential)] private struct Metrics { public uint struct_size, abi_version; public ulong emitted_token_count, queue_depth, elapsed_milliseconds; }
        [StructLayout(LayoutKind.Sequential)] private struct Event { public uint struct_size, abi_version, type, is_terminal; public ulong sequence; public IntPtr payload_utf8; public uint payload_bytes, reserved; public Metrics metrics; }
        private static class Native { private const string Lib = "llmcore"; [DllImport(Lib, EntryPoint = "hc_llm_runtime_create")] internal static extern int runtime_create(ref RuntimeOptions o, out IntPtr h); [DllImport(Lib, EntryPoint = "hc_llm_runtime_destroy")] internal static extern int runtime_destroy(IntPtr h); [DllImport(Lib, EntryPoint = "hc_llm_model_load", CharSet = CharSet.Ansi)] internal static extern int model_load(IntPtr r, string p, ref ModelLoadOptions o, out IntPtr h); [DllImport(Lib, EntryPoint = "hc_llm_model_unload")] internal static extern int model_unload(IntPtr h); [DllImport(Lib, EntryPoint = "hc_llm_model_get_metadata")] internal static extern int model_metadata(IntPtr h, ref ModelMetadata m); [DllImport(Lib, EntryPoint = "hc_llm_context_create")] internal static extern int context_create(IntPtr m, ref ContextOptions o, out IntPtr h); [DllImport(Lib, EntryPoint = "hc_llm_context_reset")] internal static extern int context_reset(IntPtr h); [DllImport(Lib, EntryPoint = "hc_llm_context_destroy")] internal static extern int context_destroy(IntPtr h); [DllImport(Lib, EntryPoint = "hc_llm_job_start")] internal static extern int job_start(IntPtr c, ref GenerationOptions o, out IntPtr h); [DllImport(Lib, EntryPoint = "hc_llm_job_cancel")] internal static extern int job_cancel(IntPtr h); [DllImport(Lib, EntryPoint = "hc_llm_job_poll")] internal static extern int job_poll(IntPtr h, ref Event e); [DllImport(Lib, EntryPoint = "hc_llm_job_destroy")] internal static extern int job_destroy(IntPtr h); }
    }
}
